"""agregando campo para correo electrónico

Revision ID: 393152efbf85
Revises: e5f03dd40c9a
Create Date: 2023-09-10 02:04:41.848103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393152efbf85'
down_revision: Union[str, None] = 'e5f03dd40c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('Correo', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_Usuarios_Correo'), 'Usuarios', ['Correo'], unique=True)
    op.create_index(op.f('ix_Usuarios_ID'), 'Usuarios', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Usuarios_ID'), table_name='Usuarios')
    op.drop_index(op.f('ix_Usuarios_Correo'), table_name='Usuarios')
    op.drop_column('Usuarios', 'Correo')
    # ### end Alembic commands ###
