"""corrigiendo nombre de tabla

Revision ID: 45e27fed1273
Revises: d00dcf987378
Create Date: 2023-09-10 02:48:00.425690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e27fed1273'
down_revision: Union[str, None] = 'd00dcf987378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Alumnos', 'Tareas', ['TareasAsignadas'], ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Alumnos', type_='foreignkey')
    # ### end Alembic commands ###
