"""agregando columna de contraseña

Revision ID: b46e8416589d
Revises: 45e27fed1273
Create Date: 2023-09-10 04:39:40.366048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46e8416589d'
down_revision: Union[str, None] = '45e27fed1273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('Password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Usuarios', 'Password')
    # ### end Alembic commands ###
