"""primeros schemas

Revision ID: c659b39a6fa8
Revises: 
Create Date: 2023-09-03 07:03:48.592834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c659b39a6fa8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Alumnos', sa.Column('EncargadoID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Alumnos', 'Encargados', ['EncargadoID'], ['ID'])
    op.alter_column('Grados', 'NombreGrado',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('Roles', 'NombreRol',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Roles', 'NombreRol',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('Grados', 'NombreGrado',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'Alumnos', type_='foreignkey')
    op.drop_column('Alumnos', 'EncargadoID')
    op.create_table('tasks',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tasks_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_index('ix_tasks_title', 'tasks', ['title'], unique=False)
    op.create_index('ix_tasks_id', 'tasks', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='posts_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_index('ix_posts_title', 'posts', ['title'], unique=False)
    op.create_index('ix_posts_id', 'posts', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_index('ix_profiles_id', 'profiles', ['id'], unique=False)
    # ### end Alembic commands ###
