"""agregando indice a tabla Tarea

Revision ID: d00dcf987378
Revises: 393152efbf85
Create Date: 2023-09-10 02:13:34.700003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00dcf987378'
down_revision: Union[str, None] = '393152efbf85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Tareas_ID'), 'Tareas', ['ID'], unique=False)
    op.create_index(op.f('ix_Usuarios_Correo'), 'Usuarios', ['Correo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Usuarios_Correo'), table_name='Usuarios')
    op.drop_index(op.f('ix_Tareas_ID'), table_name='Tareas')
    # ### end Alembic commands ###
